[context.production.environment]
  HUGO_VERSION = "0.31"

/convertidos      https://convertidos.netlify.com/
/forum            http://forum.tableless.com.br
/servicos         https://servicos.netlify.com/