---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
- type: directory
  path: content/convertidos
  label: Convertidos
  create: all
  match: "**/*"
- type: directory
  path: content/todos-os-posts
  label: Todos os posts
  create: all
  match: "**/*"
- type: directory
  path: content/forum
  label: Forum
  create: all
  match: "**/*"
- type: directory
  path: content/servicos
  label: Servicos
  create: all
  match: "**/*"
- type: directory
  path: content/pages
  label: Pages
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.44'
